# Generated by Django 4.1.3 on 2022-11-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensor',
            new_name='Sensorr',
        ),
    ]
